name: Package and release
on:
    push:
        branches:
            - main
        tags:
            - '**'
jobs:
    release:
        runs-on: ubuntu-latest
        env:
            GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - name: Clone project
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1
            - name: Package and release
              uses: BigWigsMods/packager@v2
